/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
        
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author negis
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        DefaultCategoryDataset dcd=new DefaultCategoryDataset();
        dcd.setValue(50, "Rating", "INFO 5100");
        dcd.setValue(50, "Rating", "INFO 6100");
        dcd.setValue(50, "Rating", "ENCP 6000");
        dcd.setValue(50, "Rating", "INFO 6969");
        dcd.setValue(50, "Rating", "INFO 6210");
        dcd.setValue(50, "Rating", "INFO 5454");
        JFreeChart barchart=ChartFactory.createBarChart("Subject Rating", "Subject Name", "Subject Rating", dcd);
        CategoryPlot barchrt=barchart.getCategoryPlot();
        barchrt.setRangeGridlinePaint(Color.ORANGE);
        ChartPanel barpanel=new ChartPanel(barchart);
        chart_pane.add(barpanel);
        chart_pane.validate();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        nev_bar = new javax.swing.JPanel();
        btn_student = new javax.swing.JButton();
        btn_dash = new javax.swing.JButton();
        main_dash = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_stud = new javax.swing.JTable();
        chart_pane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        nev_bar.setBackground(new java.awt.Color(255, 102, 102));

        btn_student.setBackground(new java.awt.Color(255, 102, 102));
        btn_student.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_student.setForeground(new java.awt.Color(255, 255, 255));
        btn_student.setText("Student Directory");
        btn_student.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_student.setBorderPainted(false);
        btn_student.setOpaque(false);
        btn_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_studentMouseClicked(evt);
            }
        });
        btn_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studentActionPerformed(evt);
            }
        });

        btn_dash.setBackground(new java.awt.Color(255, 102, 102));
        btn_dash.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_dash.setForeground(new java.awt.Color(255, 255, 255));
        btn_dash.setText("Dashboard");
        btn_dash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_dash.setBorderPainted(false);
        btn_dash.setOpaque(false);
        btn_dash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashMouseClicked(evt);
            }
        });
        btn_dash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nev_barLayout = new javax.swing.GroupLayout(nev_bar);
        nev_bar.setLayout(nev_barLayout);
        nev_barLayout.setHorizontalGroup(
            nev_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nev_barLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(btn_student, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
            .addGroup(nev_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(nev_barLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(btn_dash, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(659, Short.MAX_VALUE)))
        );
        nev_barLayout.setVerticalGroup(
            nev_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nev_barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_student, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(nev_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(nev_barLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btn_dash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jSplitPane1.setTopComponent(nev_bar);

        main_dash.setBackground(new java.awt.Color(255, 255, 255));

        tab_stud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Mohit Shimpi", "123AB", "3.8", "Information Sustems", "2015", "Tech Lead", "25"},
                {"2", "Vaishnavi Patole", "123AC", "3.4", "Information Sustems", "2015", "Junior Developer", "3"},
                {"3", "Nisarg Patel", "123AD", "2.5", "Information Systems", "2015", "Junior Data Analyst", "2.5"},
                {"4", "Prassanna Teja", "124AB", "3.3", "Engineering Management", "2016", "Sales Head", "10"}
            },
            new String [] {
                "Sr. No.", "Student Name", "Student ID", "GPA", "Department", "Year of Passing", "Current Position", "Salary Hike"
            }
        ));
        jScrollPane1.setViewportView(tab_stud);
        if (tab_stud.getColumnModel().getColumnCount() > 0) {
            tab_stud.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout chart_paneLayout = new javax.swing.GroupLayout(chart_pane);
        chart_pane.setLayout(chart_paneLayout);
        chart_paneLayout.setHorizontalGroup(
            chart_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chart_paneLayout.setVerticalGroup(
            chart_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout main_dashLayout = new javax.swing.GroupLayout(main_dash);
        main_dash.setLayout(main_dashLayout);
        main_dashLayout.setHorizontalGroup(
            main_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_dashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                    .addComponent(chart_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        main_dashLayout.setVerticalGroup(
            main_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_dashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(main_dash);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_studentActionPerformed

    private void btn_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_studentMouseClicked
        // TODO add your handling code here:
        studentPane studentPanel=new studentPane();
        jSplitPane1.setBottomComponent(studentPanel);
        
        
    }//GEN-LAST:event_btn_studentMouseClicked

    private void btn_dashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashActionPerformed

    private void btn_dashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashMouseClicked
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(main_dash);
    }//GEN-LAST:event_btn_dashMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dash;
    private javax.swing.JButton btn_student;
    private javax.swing.JPanel chart_pane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel main_dash;
    private javax.swing.JPanel nev_bar;
    private javax.swing.JTable tab_stud;
    // End of variables declaration//GEN-END:variables
}
