/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JSplitPane;

/**
 *
 * @author negis
 */
public class studentPane extends javax.swing.JPanel {

    /**
     * Creates new form studentPane
     */
    public studentPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_split = new javax.swing.JSplitPane();
        stud_side = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        stud_main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "Information Systems", "Engineering Management", "Financial Mathematics" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stud_sideLayout = new javax.swing.GroupLayout(stud_side);
        stud_side.setLayout(stud_sideLayout);
        stud_sideLayout.setHorizontalGroup(
            stud_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_sideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        stud_sideLayout.setVerticalGroup(
            stud_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_sideLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        student_split.setLeftComponent(stud_side);

        stud_main.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setText("Select Your Department");

        javax.swing.GroupLayout stud_mainLayout = new javax.swing.GroupLayout(stud_main);
        stud_main.setLayout(stud_mainLayout);
        stud_mainLayout.setHorizontalGroup(
            stud_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_mainLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        stud_mainLayout.setVerticalGroup(
            stud_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_mainLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        student_split.setRightComponent(stud_main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(student_split)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(student_split)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selected=jComboBox1.getSelectedItem().toString();
        information_sys info=new information_sys();
        engi_mana engi=new engi_mana();
        finan_math finan=new finan_math();
        if(selected.equals("Information Systems")){
            student_split.setRightComponent(info);
        }
        else if(selected.equals("Engineering Management")){
            student_split.setRightComponent(engi);
        }
        else if(selected.equals("Financial Mathematics")){
            student_split.setRightComponent(finan);
            
        }
        else{
            student_split.setRightComponent(stud_main);
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel stud_main;
    private javax.swing.JPanel stud_side;
    private javax.swing.JSplitPane student_split;
    // End of variables declaration//GEN-END:variables
}
