/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Request.ModifyMedicinesRequest;
import Business.Request.Order;
import Business.Request.PurchaseRequest;
import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZHOU
 */
public class PharmacyManagerWorkArea extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    /** Creates new form AdminWorkAreaJPanel */
    public PharmacyManagerWorkArea(JPanel userProcessContainer, Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        valueLabel.setText(enterprise.getName());
        
        populatemodifyMenuJTable();
        populatePurchaseTable();
        populateOrderTable();
    }
    private void populateOrderTable(){
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        for (Order o : system.getOrderDirectory().getOrderList()){
            if(o.getStatus().equals("Ordered")&&o.getRName().equals(enterprise.getName())){
                Object[] row = new Object[5];
                row[0] = o;
                row[1] = o.gettPrice();
                row[2] = o.getRName();
                row[3] = o.getDName();
                row[4] = o.getStatus();
                model.addRow(row);
            
            
        }
    }
    }
    void populatemodifyMenuJTable(){
        DefaultTableModel model = (DefaultTableModel) menuJTable.getModel();
        model.setRowCount(0);
        for (ModifyMedicinesRequest m : enterprise.getModifyDishesRequestDirectory().getModifyMenuRequestList()){
            if(m.getModifyStatus().equals("Processing")){
            Object[] row = new Object[5];
            row[0] = m.getMedicine().getMedicineName();
            row[1] = m.getoPrice();
            row[2] = m.getFp();
            row[3] = m;
            row[4] = m.getModifyStatus();
            model.addRow(row);
            }
        }
    }
    
    void populatePurchaseTable(){
        DefaultTableModel model = (DefaultTableModel) purchaseJTable.getModel();
        model.setRowCount(0);
        for (PurchaseRequest p : enterprise.getPurchaseRequestDirectory().getPurchaseRequestList()){
            if(p.getMedicineRequest().equals("Processing")){
                Object[] row = new Object[4];
                row[0] = p.getMedicineName();
                row[1] = p.gettRate();
                row[2] = p;
                row[3] = p.getMedicineRequest();
                model.addRow(row);
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageOrganizationJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnMApprove = new javax.swing.JButton();
        btnMDecline = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        purchaseJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnPApprove = new javax.swing.JButton();
        btnPDecline = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pharmacy Manager");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 540, -1));

        manageOrganizationJButton.setBackground(new java.awt.Color(0, 153, 153));
        manageOrganizationJButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        manageOrganizationJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageOrganizationJButton.setText("Manage Employee Type");
        manageOrganizationJButton.setOpaque(true);
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 130, -1));

        userJButton.setBackground(new java.awt.Color(0, 153, 153));
        userJButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        userJButton.setForeground(new java.awt.Color(255, 255, 255));
        userJButton.setText("Manage User");
        userJButton.setOpaque(true);
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, -1));

        manageEmployeeJButton.setBackground(new java.awt.Color(0, 153, 153));
        manageEmployeeJButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        manageEmployeeJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEmployeeJButton.setText("Manage Employee");
        manageEmployeeJButton.setOpaque(true);
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, -1));

        menuJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Medicines", "Original Price", "Modified Price", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(menuJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 510, 104));

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modify Item List Request:");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 170, 21));

        btnMApprove.setBackground(new java.awt.Color(0, 153, 153));
        btnMApprove.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnMApprove.setForeground(new java.awt.Color(255, 255, 255));
        btnMApprove.setText("Approve");
        btnMApprove.setOpaque(true);
        btnMApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMApproveActionPerformed(evt);
            }
        });
        add(btnMApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 105, -1));

        btnMDecline.setBackground(new java.awt.Color(0, 153, 153));
        btnMDecline.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnMDecline.setForeground(new java.awt.Color(255, 255, 255));
        btnMDecline.setText("Decline");
        btnMDecline.setOpaque(true);
        btnMDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMDeclineActionPerformed(evt);
            }
        });
        add(btnMDecline, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 105, -1));

        purchaseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material Name", "Money Ordered", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(purchaseJTable);
        if (purchaseJTable.getColumnModel().getColumnCount() > 0) {
            purchaseJTable.getColumnModel().getColumn(0).setResizable(false);
            purchaseJTable.getColumnModel().getColumn(1).setResizable(false);
            purchaseJTable.getColumnModel().getColumn(2).setResizable(false);
            purchaseJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 510, 100));

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Purchase Request:");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 134, 21));

        btnPApprove.setBackground(new java.awt.Color(0, 153, 153));
        btnPApprove.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnPApprove.setForeground(new java.awt.Color(255, 255, 255));
        btnPApprove.setText("Approve");
        btnPApprove.setOpaque(true);
        btnPApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPApproveActionPerformed(evt);
            }
        });
        add(btnPApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 105, -1));

        btnPDecline.setBackground(new java.awt.Color(0, 153, 153));
        btnPDecline.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnPDecline.setForeground(new java.awt.Color(255, 255, 255));
        btnPDecline.setText("Decline");
        btnPDecline.setOpaque(true);
        btnPDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDeclineActionPerformed(evt);
            }
        });
        add(btnPDecline, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 105, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Price", "Pharmacy", "Delivery", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 510, 97));

        jLabel4.setBackground(new java.awt.Color(0, 204, 204));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Manage Order");
        jLabel4.setOpaque(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 130, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Prepared");
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 105, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 670, 70));

        jSeparator2.setBackground(new java.awt.Color(0, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(0, 153, 153));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 670, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        PharmacyEmployeeTypeManagementJPanel manageOrganizationJPanel = new PharmacyEmployeeTypeManagementJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),system,enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        PharmacyManageUserAccountJPanel muajp = new PharmacyManageUserAccountJPanel(userProcessContainer, enterprise,system);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        PharmacyManageEmployeeJPanel manageEmployeeJPanel = new PharmacyManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),system,enterprise);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void btnPApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPApproveActionPerformed
        // TODO add your handling code here:
        int selectedrow = purchaseJTable.getSelectedRow();

        if(selectedrow >=0)
        {
            PurchaseRequest  vs = (PurchaseRequest)purchaseJTable.getValueAt(selectedrow,2);
            
            vs.setMedicineRequest("Approved By Manager");
            
            
            
            JOptionPane.showMessageDialog(null, "This request has been approved!!");
            populatePurchaseTable();
        }
        else
        JOptionPane.showMessageDialog(null,"Please select an request!! ");
    }//GEN-LAST:event_btnPApproveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedrow = jTable2.getSelectedRow();

        if(selectedrow >=0)
        {
            Order  vs = (Order)jTable2.getValueAt(selectedrow,0);
            
            vs.setStatus("Prepared");
            
            
            JOptionPane.showMessageDialog(null, "This order has been prepared");
            populateOrderTable();
        }
        else
        JOptionPane.showMessageDialog(null,"Please select an order to manage ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnMApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMApproveActionPerformed
        // TODO add your handling code here:
        int selectedrow = menuJTable.getSelectedRow();

        if(selectedrow >=0)
        {
            ModifyMedicinesRequest  vs = (ModifyMedicinesRequest)menuJTable.getValueAt(selectedrow,3);
            
            vs.setModifyStatus("Approved");
            
            vs.getMedicine().setPrice(vs.getFp());
            
            
            JOptionPane.showMessageDialog(null, "This request has been approved!!");
            populatemodifyMenuJTable();
        }
        else
        JOptionPane.showMessageDialog(null,"Please select an request!! ");
    }//GEN-LAST:event_btnMApproveActionPerformed

    private void btnMDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMDeclineActionPerformed
        // TODO add your handling code here:
        int selectedrow = menuJTable.getSelectedRow();

        if(selectedrow >=0)
        {
            ModifyMedicinesRequest  vs = (ModifyMedicinesRequest)menuJTable.getValueAt(selectedrow,3);
            
            vs.setModifyStatus("Declined");
            
            
            
            JOptionPane.showMessageDialog(null, "This request has been declined!!");
            populatemodifyMenuJTable();
            
            
                
        }
        else
        JOptionPane.showMessageDialog(null,"Please select an request!! ");
    }//GEN-LAST:event_btnMDeclineActionPerformed

    private void btnPDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDeclineActionPerformed
        // TODO add your handling code here:
        int selectedrow = purchaseJTable.getSelectedRow();

        if(selectedrow >=0)
        {
            PurchaseRequest  vs = (PurchaseRequest)purchaseJTable.getValueAt(selectedrow,2);
            
            vs.setMedicineRequest("Declined By Manager");
            
            
            
            JOptionPane.showMessageDialog(null, "This request has been Declined!!");
            populatePurchaseTable();
        }
        else
        JOptionPane.showMessageDialog(null,"Please select an request!! ");
    }//GEN-LAST:event_btnPDeclineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMApprove;
    private javax.swing.JButton btnMDecline;
    private javax.swing.JButton btnPApprove;
    private javax.swing.JButton btnPDecline;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JTable menuJTable;
    private javax.swing.JTable purchaseJTable;
    private javax.swing.JButton userJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
