/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.DPAdminRole;
import Business.Role.PManagerRole;
import Business.Role.RManagerRole;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mohit_shimpi
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateNetworkComboBox();
    }
    
     private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Employee employee;
                    employee = new Employee();
                    Object[] row = new Object[5];
                    row[0] = enterprise;
                    row[1] = enterprise.getEnterpriseType();
                    row[2] = network.getName();
                    row[3] = userAccount.getUsername();
                    row[4] = userAccount.getPassword();

                    model.addRow(row);
                }
            }
        }
    }

    private void populateNetworkComboBox(){
        networkJComboBox.removeAllItems();
        
        for (Network network : system.getNetworkList()){
            networkJComboBox.addItem(network);
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        enterpriseJComboBox.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            enterpriseJComboBox.addItem(enterprise);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enterpriseJComboBox = new javax.swing.JComboBox();
        addbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        enterprisenameJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();
        AreaNAmeJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        networkJComboBox.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        networkJComboBox.setForeground(new java.awt.Color(0, 0, 102));
        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        add(networkJComboBox);
        networkJComboBox.setBounds(670, 100, 200, 25);

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Username:");
        jLabel2.setOpaque(true);
        add(jLabel2);
        jLabel2.setBounds(550, 240, 110, 19);
        add(userNameJTextField);
        userNameJTextField.setBounds(670, 230, 200, 30);

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enterprise:");
        jLabel3.setOpaque(true);
        add(jLabel3);
        jLabel3.setBounds(550, 140, 110, 19);

        enterpriseJComboBox.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        enterpriseJComboBox.setForeground(new java.awt.Color(0, 0, 102));
        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterpriseJComboBox);
        enterpriseJComboBox.setBounds(670, 140, 210, 25);

        addbutton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        addbutton.setForeground(new java.awt.Color(0, 204, 204));
        addbutton.setText("Add");
        addbutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        add(addbutton);
        addbutton.setBounds(940, 290, 100, 30);

        jLabel4.setBackground(new java.awt.Color(0, 204, 204));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password:");
        jLabel4.setOpaque(true);
        add(jLabel4);
        jLabel4.setBounds(550, 290, 110, 19);
        add(enterprisenameJTextField);
        enterprisenameJTextField.setBounds(670, 180, 200, 30);

        enterpriseJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enterpriseJTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Enterprise ", "Enterprise Type", "Network", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterpriseJTable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(enterpriseJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(520, 340, 550, 240);

        jLabel5.setBackground(new java.awt.Color(0, 204, 204));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Name:");
        jLabel5.setOpaque(true);
        add(jLabel5);
        jLabel5.setBounds(550, 190, 110, 19);

        passwordField.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        passwordField.setForeground(new java.awt.Color(0, 0, 102));
        add(passwordField);
        passwordField.setBounds(670, 280, 200, 30);

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Network:");
        jLabel1.setOpaque(true);
        add(jLabel1);
        jLabel1.setBounds(550, 110, 110, 19);

        wallpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin_1.gif"))); // NOI18N
        add(wallpaper);
        wallpaper.setBounds(10, 180, 510, 290);

        AreaNAmeJLabel.setBackground(new java.awt.Color(0, 204, 204));
        AreaNAmeJLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        AreaNAmeJLabel.setForeground(new java.awt.Color(255, 255, 255));
        AreaNAmeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AreaNAmeJLabel.setText("Enterprise Admin");
        AreaNAmeJLabel.setOpaque(true);
        add(AreaNAmeJLabel);
        AreaNAmeJLabel.setBounds(130, 60, 200, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed

        Network network = (Network) networkJComboBox.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
        }

    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed

        Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();

        String username = userNameJTextField.getText();
        String password = String.valueOf(passwordField.getPassword());
        String name = enterprisenameJTextField.getText();
        
        
        if(username.isEmpty()||password.isEmpty()||name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter enterprise name!","Warning", JOptionPane.WARNING_MESSAGE);
            return;     
        }
     
     
            for(Employee en : enterprise.getEmployeeDirectory().getEmployeeList()){
                if(en.getName().equals(name)){
                    JOptionPane.showMessageDialog(null, "Enterprise already exist!","Warning",JOptionPane.WARNING_MESSAGE);
                return;
                }
            }
            for(UserAccount ua: enterprise.getUserAccountDirectory().getUserAccountList()){
                if(ua.getUsername().equals(username)){
                    JOptionPane.showMessageDialog(null, "Enterprise already exist!","Warning",JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
           
        Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);
        if(enterprise.getEnterpriseType().toString().equals("Delivery Partner"))
        { 
            UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new DPAdminRole());
            JOptionPane.showMessageDialog(null, "Delivery Partner Created Successfully!","Success",JOptionPane.PLAIN_MESSAGE);
        }
        if(enterprise.getEnterpriseType().toString().equals("Finance Partner"))
        {
            UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new PManagerRole());
            JOptionPane.showMessageDialog(null, " Finance Partner Created Successfully","Success",JOptionPane.PLAIN_MESSAGE);
        }
        if(enterprise.getEnterpriseType().toString().equals("Pharmacy"))
        {
            UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new RManagerRole());
            JOptionPane.showMessageDialog(null, "Pharmacy Created Successfully","Success",JOptionPane.PLAIN_MESSAGE);
        }
        
        dB4OUtil.storeSystem(system);
        populateTable();
        
        enterprisenameJTextField.setText("");
        userNameJTextField.setText("");
        passwordField.setText("");
    }//GEN-LAST:event_addbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AreaNAmeJLabel;
    private javax.swing.JButton addbutton;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JTextField enterprisenameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameJTextField;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
