/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.EcoSystem;
import javax.swing.JPanel;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mohit_shimpi
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateComboBox();
        
    }
      
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = enterprise;
                row[1] = network;
                row[2] = enterprise.getEnterpriseType().getValue();
                model.addRow(row);
            }
        }
    }
    
    private void populateComboBox() {
        NetworkComboBox.removeAllItems();
        EnterpriseComboBox.removeAllItems();

        for (Network network : system.getNetworkList()) {
            NetworkComboBox.addItem(network);
        }
        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            EnterpriseComboBox.addItem(type);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        NetworkLabel = new javax.swing.JLabel();
        NetworkComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        enterpriseNameTextField = new javax.swing.JTextField();
        EnterpriseLabel = new javax.swing.JLabel();
        EnterpriseComboBox = new javax.swing.JComboBox();
        AddJButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();
        AreaNAmeJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        enterpriseJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enterpriseJTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise", "Area", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterpriseJTable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(enterpriseJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(680, 220, 570, 190);

        NetworkLabel.setBackground(new java.awt.Color(0, 204, 204));
        NetworkLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        NetworkLabel.setForeground(new java.awt.Color(255, 255, 255));
        NetworkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NetworkLabel.setText("Area:");
        NetworkLabel.setOpaque(true);
        add(NetworkLabel);
        NetworkLabel.setBounds(670, 60, 150, 19);

        NetworkComboBox.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        NetworkComboBox.setForeground(new java.awt.Color(0, 0, 102));
        NetworkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        NetworkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NetworkComboBoxActionPerformed(evt);
            }
        });
        add(NetworkComboBox);
        NetworkComboBox.setBounds(860, 50, 160, 30);

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enterprise :");
        jLabel2.setOpaque(true);
        add(jLabel2);
        jLabel2.setBounds(670, 150, 150, 20);

        enterpriseNameTextField.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        enterpriseNameTextField.setForeground(new java.awt.Color(0, 0, 102));
        enterpriseNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseNameTextFieldActionPerformed(evt);
            }
        });
        add(enterpriseNameTextField);
        enterpriseNameTextField.setBounds(860, 150, 210, 30);

        EnterpriseLabel.setBackground(new java.awt.Color(0, 204, 204));
        EnterpriseLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        EnterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        EnterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnterpriseLabel.setText("Enterprise Type:");
        EnterpriseLabel.setOpaque(true);
        add(EnterpriseLabel);
        EnterpriseLabel.setBounds(670, 100, 150, 20);

        EnterpriseComboBox.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        EnterpriseComboBox.setForeground(new java.awt.Color(0, 0, 102));
        EnterpriseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        EnterpriseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterpriseComboBoxActionPerformed(evt);
            }
        });
        add(EnterpriseComboBox);
        EnterpriseComboBox.setBounds(860, 100, 190, 30);

        AddJButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        AddJButton.setForeground(new java.awt.Color(0, 204, 204));
        AddJButton.setText("Add");
        AddJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        AddJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddJButtonActionPerformed(evt);
            }
        });
        add(AddJButton);
        AddJButton.setBounds(1120, 150, 80, 30);

        deleteButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(0, 204, 204));
        deleteButton.setText("Delete");
        deleteButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton);
        deleteButton.setBounds(1030, 430, 160, 30);

        wallpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/organization.gif"))); // NOI18N
        add(wallpaper);
        wallpaper.setBounds(10, 100, 610, 440);

        AreaNAmeJLabel.setBackground(new java.awt.Color(0, 204, 204));
        AreaNAmeJLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        AreaNAmeJLabel.setForeground(new java.awt.Color(255, 255, 255));
        AreaNAmeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AreaNAmeJLabel.setText("Add Enterprise");
        AreaNAmeJLabel.setOpaque(true);
        add(AreaNAmeJLabel);
        AreaNAmeJLabel.setBounds(160, 20, 330, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void EnterpriseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterpriseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterpriseComboBoxActionPerformed

    private void AddJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddJButtonActionPerformed

        Network network = (Network) NetworkComboBox.getSelectedItem();
        Enterprise.EnterpriseType enterpriseType = (Enterprise.EnterpriseType) EnterpriseComboBox.getSelectedItem();
        String enterpriseName = enterpriseNameTextField.getText();
        
        populateTable();
     
        if(enterpriseName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter enterprise name!","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
       
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            if(enterprise.getName().equals(enterpriseName)){
                JOptionPane.showMessageDialog(null, "Enterprise already exist!","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(enterpriseName, enterpriseType);
        JOptionPane.showMessageDialog(null, "Enterprise added successfully!","Success", JOptionPane.PLAIN_MESSAGE);
        populateTable();
        
        dB4OUtil.storeSystem(system);
        enterpriseNameTextField.setText("");
        
    }//GEN-LAST:event_AddJButtonActionPerformed
  
    private void enterpriseNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseNameTextFieldActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int row = enterpriseJTable.getSelectedRow();

        if(row <0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row!","Warning",JOptionPane.WARNING_MESSAGE );
        }
        Enterprise  enterprise = (Enterprise)enterpriseJTable.getValueAt(row,0);
        Network network = (Network)enterpriseJTable.getValueAt(row,1);
        
        network.getEnterpriseDirectory().getEnterpriseList().remove(enterprise);

        JOptionPane.showMessageDialog(null, "Enterprise has been deleted!","Success", JOptionPane.PLAIN_MESSAGE);
        populateTable();
     
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void NetworkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NetworkComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NetworkComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddJButton;
    private javax.swing.JLabel AreaNAmeJLabel;
    private javax.swing.JComboBox EnterpriseComboBox;
    private javax.swing.JLabel EnterpriseLabel;
    private javax.swing.JComboBox NetworkComboBox;
    private javax.swing.JLabel NetworkLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JTextField enterpriseNameTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables

}
