/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmacyManagerRole;

import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Organization.PharmacyManagerOrganization;
import Business.Request.Medicine;
import Business.Request.ModifyMedicinesRequest;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZHOU
 */
public class ManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private PharmacyManagerOrganization cookOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

  
    public ManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, PharmacyManagerOrganization cookOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.cookOrganization = cookOrganization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        valueLabel.setText(enterprise.getName());
        
        populateMenuTable();
        populatemodifyMenuJTable();
    }
    
    void populateMenuTable(){
        DefaultTableModel model = (DefaultTableModel) menuJTable.getModel();
        model.setRowCount(0);
        for (Medicine d : enterprise.getMenu().getMedicineList()){
            Object[] row = new Object[2];
            row[0] = d;
            row[1] = d.getPrice();
            model.addRow(row);
        }
    }
    
    void populatemodifyMenuJTable(){
        DefaultTableModel model = (DefaultTableModel) modifyMenuJTable.getModel();
        model.setRowCount(0);
        for (ModifyMedicinesRequest m : enterprise.getModifyDishesRequestDirectory().getModifyMenuRequestList()){
            Object[] row = new Object[5];
            row[0] = m.getMedicine().getMedicineName();
            row[1] = m.getoPrice();
            row[2] = m.getFp();
            row[3] = m;
            row[4] = m.getModifyStatus();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        modifyMenuJTable = new javax.swing.JTable();
        btnModifyMenu = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        menuJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modifyMenuJTable.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        modifyMenuJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Original Price", "Modified Price", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(modifyMenuJTable);
        if (modifyMenuJTable.getColumnModel().getColumnCount() > 0) {
            modifyMenuJTable.getColumnModel().getColumn(0).setResizable(false);
            modifyMenuJTable.getColumnModel().getColumn(1).setResizable(false);
            modifyMenuJTable.getColumnModel().getColumn(2).setResizable(false);
            modifyMenuJTable.getColumnModel().getColumn(3).setResizable(false);
            modifyMenuJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 480, 104));

        btnModifyMenu.setBackground(new java.awt.Color(0, 153, 153));
        btnModifyMenu.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnModifyMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnModifyMenu.setText("Modify Request");
        btnModifyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyMenuActionPerformed(evt);
            }
        });
        add(btnModifyMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 158, -1));

        valueLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 8, 158, 26));

        enterpriseLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, 94, 30));

        menuJTable.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        menuJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(menuJTable);
        if (menuJTable.getColumnModel().getColumnCount() > 0) {
            menuJTable.getColumnModel().getColumn(0).setResizable(false);
            menuJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 480, 104));

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ITEM:");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 85, -1));

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modify Menu Request:");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 200, -1));

        btnAdd.setBackground(new java.awt.Color(0, 153, 153));
        btnAdd.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Item");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 158, -1));

        btnDelete.setBackground(new java.awt.Color(0, 153, 153));
        btnDelete.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Item");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 158, -1));

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MANAGER");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 20, 300, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyMenuActionPerformed
        // TODO add your handling code here:
        int selectedrow = menuJTable.getSelectedRow();

        if (selectedrow >= 0) {
            Medicine d = (Medicine) menuJTable.getValueAt(selectedrow, 0);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("RequestModifyMenuJPanel", new RequestModifyListJPanel(userProcessContainer, userAccount, enterprise, d, business));
            layout.next(userProcessContainer);
        } else
        JOptionPane.showMessageDialog(null, "Please select any row");
        
    }//GEN-LAST:event_btnModifyMenuActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddMedicinesJPanel ad = new AddMedicinesJPanel(userProcessContainer,enterprise.getMenu(),business,enterprise);
        userProcessContainer.add("AddDishJPanel", ad);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        //populateTable1();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedrow = menuJTable.getSelectedRow();

        if (selectedrow >= 0) {
            Medicine d = (Medicine) menuJTable.getValueAt(selectedrow, 0);
            enterprise.getMenu().deleteDish(d);
            DB4OUtil.getInstance().storeSystem(business);
            JOptionPane.showMessageDialog(null, "Organization has been deleted");
            populateMenuTable();
        } else
        JOptionPane.showMessageDialog(null, "Please select any row");
    
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModifyMenu;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable menuJTable;
    private javax.swing.JTable modifyMenuJTable;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
