/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.Network.Network;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mohit_shimpi
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form ManageNetworkJPanel
     */
    public ManageNetworkJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateNetworkTable();
    }
    
    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) NetworkJTabel.getModel();
        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network;
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        NetworkJTabel = new javax.swing.JTable();
        AreaNAmeJLabel = new javax.swing.JLabel();
        AddJButton = new javax.swing.JButton();
        AreaNameJText = new javax.swing.JTextField();
        DeleteJButton = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        NetworkJTabel.setAutoCreateRowSorter(true);
        NetworkJTabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NetworkJTabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        NetworkJTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        NetworkJTabel.setFocusTraversalPolicyProvider(true);
        NetworkJTabel.setFocusable(false);
        NetworkJTabel.setGridColor(new java.awt.Color(51, 51, 51));
        NetworkJTabel.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(NetworkJTabel);

        add(jScrollPane1);
        jScrollPane1.setBounds(540, 190, 480, 190);

        AreaNAmeJLabel.setBackground(new java.awt.Color(0, 204, 204));
        AreaNAmeJLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        AreaNAmeJLabel.setForeground(new java.awt.Color(255, 255, 255));
        AreaNAmeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AreaNAmeJLabel.setText("Add Area");
        AreaNAmeJLabel.setOpaque(true);
        add(AreaNAmeJLabel);
        AreaNAmeJLabel.setBounds(160, 20, 200, 40);

        AddJButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        AddJButton.setForeground(new java.awt.Color(0, 153, 153));
        AddJButton.setText("Add");
        AddJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        AddJButton.setMaximumSize(new java.awt.Dimension(37, 19));
        AddJButton.setMinimumSize(new java.awt.Dimension(37, 19));
        AddJButton.setPreferredSize(new java.awt.Dimension(37, 19));
        AddJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddJButtonActionPerformed(evt);
            }
        });
        add(AddJButton);
        AddJButton.setBounds(850, 140, 100, 30);

        AreaNameJText.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        AreaNameJText.setForeground(new java.awt.Color(0, 0, 102));
        add(AreaNameJText);
        AreaNameJText.setBounds(640, 140, 180, 30);

        DeleteJButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        DeleteJButton.setForeground(new java.awt.Color(0, 153, 153));
        DeleteJButton.setText("Delete");
        DeleteJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        DeleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteJButtonActionPerformed(evt);
            }
        });
        add(DeleteJButton);
        DeleteJButton.setBounds(730, 410, 130, 30);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/area1.gif"))); // NOI18N
        wallpaper.setAutoscrolls(true);
        wallpaper.setOpaque(true);
        add(wallpaper);
        wallpaper.setBounds(50, 130, 440, 320);
    }// </editor-fold>//GEN-END:initComponents

    private void AddJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddJButtonActionPerformed

        String areaName = AreaNameJText.getText();
        
        if(areaName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter area name!","Warning", JOptionPane.WARNING_MESSAGE); 
            return;
        }
        
        for(Network network : system.getNetworkList()){
            if(network.getName().equals(areaName)){
                JOptionPane.showMessageDialog(null, "Area already exist!","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
     
        Network network = system.createAndAddNetwork();
        network.setName(areaName); 
        JOptionPane.showMessageDialog(null, "Area added successfully!","Success", JOptionPane.PLAIN_MESSAGE);
        populateNetworkTable();  
        
        dB4OUtil.storeSystem(system);
        AreaNameJText.setText("");
    }//GEN-LAST:event_AddJButtonActionPerformed

    private void DeleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteJButtonActionPerformed
        // TODO add your handling code here:
        int selectRow = NetworkJTabel.getSelectedRow();

        if(selectRow<0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Network  network = (Network)NetworkJTabel.getValueAt(selectRow,0);   
        system.getNetworkList().remove(network);
        JOptionPane.showMessageDialog(null, "Area deleted successfully","Success", JOptionPane.PLAIN_MESSAGE);
        populateNetworkTable();

        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_DeleteJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddJButton;
    private javax.swing.JLabel AreaNAmeJLabel;
    private javax.swing.JTextField AreaNameJText;
    private javax.swing.JButton DeleteJButton;
    private javax.swing.JTable NetworkJTabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
