/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Employee.Employee;
import Business.Role.CustomerRole;
import Business.EcoSystem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.DB4OUtil.DB4OUtil;
import Business.Employee.EmployeeDirectory;
import Business.UserAccount.UserAccount;

/**
 *
 * @author HYY
 */
public class RegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterJPanel
     */
    JPanel userProcessContainer;
    private EcoSystem system;
    public RegisterJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer =userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        BtnCreat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Name:");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 150, 20));

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password:");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 190, 140, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 177, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 177, -1));

        BtnCreat.setBackground(new java.awt.Color(0, 153, 153));
        BtnCreat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BtnCreat.setForeground(new java.awt.Color(255, 255, 255));
        BtnCreat.setText("Create");
        BtnCreat.setOpaque(true);
        BtnCreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreatActionPerformed(evt);
            }
        });
        add(BtnCreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("UserAccount:");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 150, 140, -1));
        add(txtNa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 177, -1));

        jLabel6.setBackground(new java.awt.Color(0, 204, 204));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customer");
        jLabel6.setOpaque(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreatActionPerformed
        // TODO add your handling code here:
        System.out.println(system);
        String name = txtNa.getText();
        EmployeeDirectory ed = system.getEmployeeDirectory();
        System.out.println(ed);
        Employee employee = null;
        String userName =txtName.getText();
        String password = txtPassword.getText();
        boolean exist=false;
        if(!txtNa.getText().equals(txtName.getText())){
            JOptionPane.showMessageDialog(null, "UserAccount and Name should be the same!");
        }
        else if(txtNa.getText().equals("")|| userName.equals("")
                    ||password.equals("")){
                 JOptionPane.showMessageDialog(null, "one or more fields are empty.");
                 return;
            }else{
            for(UserAccount userAccount: system.getUserAccountDirectory().getUserAccountList()){
                if(userAccount.getUsername().equals(userName)){
                    JOptionPane.showMessageDialog(null, "Customer already exist!");
                    exist=true;
                    break;
                }
            }
            if(exist==false){
            system.getUserAccountDirectory().createUserAccount(userName, password, employee, new CustomerRole());
            DB4OUtil.getInstance().storeSystem(system);
            JOptionPane.showMessageDialog(null, "Register Successfully");
            
            txtNa.setText("");
            txtName.setText("");
            txtPassword.setText("");
            }
        }  
        
        
    }//GEN-LAST:event_BtnCreatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtNa;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
